name: Build, Test, Secure, and Analyze

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Static Code Analysis
        run: mvn checkstyle:check

      - name: Run Tests with Coverage
        run: mvn clean test jacoco:report

      - name: Package Application
        run: mvn package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: target/*.jar

      - name: Generate Changelog
        run: npx conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Generate Application Insights
        run: |
          echo "Generating insights..."
          # Replace this with a relevant command for your application

      - name: Notify on Build Status
        run: echo "Build completed with status: ${{ job.status }}"

  notify-slack:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

